/*
 * File: app/controller/Account.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('STARApp.controller.Account', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            homeView: 'homeview',
            loginForm: 'loginform',
            mainPage: {
                autoCreate: true,
                selector: 'mainpage',
                xtype: 'mainpage'
            }
        },

        control: {
            "homeview #showLoginButton": {
                tap: 'showLogin'
            },
            "loginform #loginbutton": {
                tap: 'login'
            }
        }
    },

    showLogin: function(button, e, eOpts) {

        var homeView = this.getHomeView();				// Main view


        // Navigate to login
        homeView.push({
            xtype: "loginform",
            title: "Login"
        });


    },

    login: function(button, e, eOpts) {

        var form = button.up('formpanel'),
        	values = form.getValues(),
        	homeView = this.getHomeView(),
        	loginForm = this.getLoginForm(),
        	mainPage = this.getMainPage();

        // Success
        var successCallback = function(resp, ops) {

            // Go back
            //mainView.pop();
            homeView.hide();

            // Hide login panel
            loginForm.hide();

            // Show welcome panel
            //welcomePanel.show();

            if(!mainPage.getParent()){
                Ext.Viewport.add(mainPage);
            }

            mainPage.show();

        };

        // Failure
        var failureCallback = function(resp, ops) {

            // Show login failure error
            Ext.Msg.alert("Login Failure", resp);

        };


        debugger;
        var username = Ext.getCmp('username');
        var password = Ext.getCmp('password');

        // TODO: Login using server-side authentication service
        // Ext.Ajax.request({
        //		url: "/api/login",
        //		params: values,
        //		success: successCallback,
        //		failure: failureCallback
        // });


        console.log(username.getValue());

        if(username.getValue() == 'test' && password.getValue() == 'test')
            successCallback();
        else
            failureCallback();


    }

});