/*
 * File: app/view/HomeVIew.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('STARApp.view.HomeVIew', {
    extend: 'Ext.navigation.View',
    alias: 'widget.homeview',

    requires: [
        'Ext.Img',
        'Ext.Label',
        'Ext.Panel',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        margin: 2,
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'image',
                                height: 40,
                                width: 50,
                                src: 'resources/icons/icon_cdc.gif'
                            },
                            {
                                xtype: 'label',
                                html: 'Suspense Tracking and Routing(STAR)',
                                style: 'font-variant:small-caps; font-size:15px;',
                                width: '90%'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        itemId: 'loginPanel',
                        padding: '',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'showLoginButton',
                                margin: 25,
                                padding: 8,
                                width: '80%',
                                text: 'Login'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});