//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrItem
    {
        public int corritemid { get; set; }
        public int correspondenceid { get; set; }
        public int correspondencetypeid { get; set; }
        public Nullable<int> responsiblebranchid { get; set; }
        public Nullable<int> branchcontact { get; set; }
        public Nullable<decimal> amtreq1 { get; set; }
        public bool responserequired { get; set; }
        public string approverejectstatus { get; set; }
        public string corritemdescription { get; set; }
        public Nullable<int> approverid { get; set; }
        public string status { get; set; }
        public bool hascurrentrecommendation { get; set; }
        public bool hascurrentapproval { get; set; }
        public Nullable<decimal> amtrecommended { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
