/*
 * File: app/view/MainPage.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StarApp.view.MainPage', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainpage',

    requires: [
        'Ext.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                title: 'Home',
                items: [
                    {
                        xtype: 'panel',
                        padding: 10,
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div class="tickets-list-item">',
                                    '    <div class="importance importance-{importance}">{importance}</div>',
                                    '    {title}: {status}',
                                    '</div>'
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Search'
            },
            {
                xtype: 'container',
                title: 'Log out'
            }
        ]
    }

});